"""empty message

Revision ID: 0536132dba5a
Revises: 85472c34108f
Create Date: 2023-12-26 15:28:42.224920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0536132dba5a'
down_revision = '85472c34108f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Lexicon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=50), nullable=False),
    sa.Column('pronunciation', sa.String(length=50), nullable=True),
    sa.Column('conscript', sa.String(length=50), nullable=True),
    sa.Column('definition', sa.String(length=255), nullable=False),
    sa.Column('partofspeech', sa.String(), nullable=True),
    sa.Column('infclass', sa.String(length=10), nullable=True),
    sa.Column('wordclass', sa.String(length=1), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('etymology', sa.String(), nullable=True),
    sa.Column('irregular', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Lexicon', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Lexicon_definition'), ['definition'], unique=False)
        batch_op.create_index(batch_op.f('ix_Lexicon_word'), ['word'], unique=False)

    with op.batch_alter_table('lexicon', schema=None) as batch_op:
        batch_op.drop_index('ix_lexicon_definition')
        batch_op.drop_index('ix_lexicon_word')

    op.drop_table('lexicon')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lexicon',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('word', sa.TEXT(length=50), nullable=False),
    sa.Column('pronunciation', sa.TEXT(length=50), nullable=True),
    sa.Column('conscript', sa.TEXT(length=50), nullable=True),
    sa.Column('definition', sa.TEXT(length=255), nullable=False),
    sa.Column('partofspeech', sa.TEXT(length=1), nullable=False),
    sa.Column('infclass', sa.TEXT(length=10), nullable=True),
    sa.Column('wordclass', sa.TEXT(length=1), nullable=True),
    sa.Column('notes', sa.VARCHAR(), nullable=True),
    sa.Column('etymology', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lexicon', schema=None) as batch_op:
        batch_op.create_index('ix_lexicon_word', ['word'], unique=False)
        batch_op.create_index('ix_lexicon_definition', ['definition'], unique=False)

    with op.batch_alter_table('Lexicon', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Lexicon_word'))
        batch_op.drop_index(batch_op.f('ix_Lexicon_definition'))

    op.drop_table('Lexicon')
    # ### end Alembic commands ###
