"""lexicon table

Revision ID: 5e5c7966ff02
Revises: 
Create Date: 2023-12-19 15:37:56.157720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e5c7966ff02'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lexicon', schema=None) as batch_op:
        batch_op.alter_column('word',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('pronunciation',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('definition',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_lexicon_definition'), ['definition'], unique=False)
        batch_op.create_index(batch_op.f('ix_lexicon_word'), ['word'], unique=False)
        batch_op.drop_column('partofspeech')
        batch_op.drop_column('notes')
        batch_op.drop_column('infclass')
        batch_op.drop_column('etymology')
        batch_op.drop_column('wordclass')
        batch_op.drop_column('conscript')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lexicon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conscript', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('wordclass', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('etymology', sa.NullType(), nullable=True))
        batch_op.add_column(sa.Column('infclass', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('partofspeech', sa.TEXT(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_lexicon_word'))
        batch_op.drop_index(batch_op.f('ix_lexicon_definition'))
        batch_op.alter_column('definition',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('pronunciation',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('word',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###
